/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GitSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var import_util = require("util");
var execAsync = (0, import_util.promisify)(import_child_process.exec);
var DEFAULT_SETTINGS = {
  vaultPath: "/home/r/Documents/Obsidian",
  autoPauseHours: 1
};
async function runGit(args, cwd) {
  return execAsync(`git ${args}`, { cwd });
}
async function hasLocalChanges(vaultPath) {
  const { stdout } = await runGit("status --porcelain", vaultPath);
  return stdout.trim().length > 0;
}
async function pushOnly(vaultPath) {
  const timestamp = (/* @__PURE__ */ new Date()).toISOString();
  const hasChanges = await hasLocalChanges(vaultPath);
  if (!hasChanges) {
    return false;
  }
  await runGit("add -A", vaultPath);
  try {
    await runGit(`commit -m "Manual push: ${timestamp}"`, vaultPath);
  } catch (e) {
  }
  await runGit("push origin main", vaultPath);
  return true;
}
async function commitAndSync(vaultPath) {
  const timestamp = (/* @__PURE__ */ new Date()).toISOString();
  const hasChanges = await hasLocalChanges(vaultPath);
  if (hasChanges) {
    await runGit("add -A", vaultPath);
    try {
      await runGit(`commit -m "Auto-sync: ${timestamp}"`, vaultPath);
    } catch (e) {
    }
  }
  await runGit("fetch origin", vaultPath);
  try {
    await runGit("rebase -X ours origin/main", vaultPath);
  } catch (e) {
    await runGit("rebase --abort", vaultPath).catch(() => {
    });
  }
  await runGit("push origin main", vaultPath);
}
var GitSyncPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.pauseUntil = 0;
    this.intervalId = null;
    this.INTERVAL_MS = 15 * 60 * 1e3;
  }
  // 15 minutes
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("upload-cloud", "Push updates to GitHub", async () => {
      await this.performPush();
    });
    this.addRibbonIcon("refresh-cw", "Sync vault with GitHub (Pull & Push)", async () => {
      await this.performSync(true);
    });
    this.addCommand({
      id: "github-push-now",
      name: "Push local vault updates to GitHub now",
      callback: async () => {
        await this.performPush();
      }
    });
    this.addCommand({
      id: "github-sync-now",
      name: "Sync vault with GitHub now (Pull & Push)",
      callback: async () => {
        await this.performSync(true);
      }
    });
    this.addSettingTab(new GitSyncSettingTab(this.app, this));
    this.startPeriodicSync();
    console.log("[GitSync] Plugin loaded.");
  }
  onunload() {
    this.stopPeriodicSync();
    console.log("[GitSync] Plugin unloaded.");
  }
  // -------------------------------------------------------------------------
  // Push local updates logic
  // -------------------------------------------------------------------------
  async performPush() {
    const vault = this.settings.vaultPath;
    try {
      new import_obsidian.Notice("\u2B06\uFE0F GitSync: checking and pushing local updates\u2026");
      const pushed = await pushOnly(vault);
      if (pushed) {
        new import_obsidian.Notice("\u2705 GitSync: local updates pushed to GitHub successfully!");
      } else {
        new import_obsidian.Notice("\u2139\uFE0F GitSync: no local changes to push.");
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error("[GitSync] Push error:", msg);
      new import_obsidian.Notice(`\u274C GitSync push error: ${msg}`);
    }
  }
  // -------------------------------------------------------------------------
  // Core sync logic (Pull & Push)
  // -------------------------------------------------------------------------
  async performSync(manual = false) {
    const vault = this.settings.vaultPath;
    const now = Date.now();
    if (!manual && now < this.pauseUntil) {
      const remainingMin = Math.ceil((this.pauseUntil - now) / 6e4);
      console.log(`[GitSync] Auto-sync paused for ${remainingMin} more minute(s).`);
      return;
    }
    try {
      const hasChanges = await hasLocalChanges(vault);
      if (!hasChanges && !manual) {
        console.log("[GitSync] No local changes detected.");
        return;
      }
      if (!hasChanges && manual) {
        await runGit("fetch origin", vault);
        await runGit("rebase origin/main", vault);
        new import_obsidian.Notice("\u2705 GitSync: pulled latest from GitHub (no local changes).");
        return;
      }
      if (!manual) {
        this.showAutoSyncNotification(vault);
        return;
      }
      new import_obsidian.Notice("\u{1F504} GitSync: syncing\u2026");
      await commitAndSync(vault);
      new import_obsidian.Notice("\u2705 GitSync: vault synced with GitHub.");
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error("[GitSync] Sync error:", msg);
      new import_obsidian.Notice(`\u274C GitSync error: ${msg}`);
    }
  }
  showAutoSyncNotification(vault) {
    new AutoSyncModal(this.app, {
      onSync: async () => {
        try {
          await commitAndSync(vault);
          new import_obsidian.Notice("\u2705 GitSync: vault auto-synced.");
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          new import_obsidian.Notice(`\u274C GitSync error: ${msg}`);
        }
      },
      onDecline: () => {
        const pauseMs = this.settings.autoPauseHours * 60 * 60 * 1e3;
        this.pauseUntil = Date.now() + pauseMs;
        new import_obsidian.Notice(
          `\u23F8\uFE0F GitSync: auto-sync paused for ${this.settings.autoPauseHours}h.`
        );
      }
    }).open();
  }
  // -------------------------------------------------------------------------
  // Periodic timer
  // -------------------------------------------------------------------------
  startPeriodicSync() {
    this.intervalId = window.setInterval(async () => {
      await this.performSync(false);
    }, this.INTERVAL_MS);
  }
  stopPeriodicSync() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }
  // -------------------------------------------------------------------------
  // Settings persistence
  // -------------------------------------------------------------------------
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var AutoSyncModal = class extends import_obsidian.Modal {
  constructor(app, options) {
    super(app);
    this.options = options;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F504} GitSync: Changes Detected" });
    contentEl.createEl("p", {
      text: "Local vault changes were detected. Sync to GitHub now?"
    });
    const btnRow = contentEl.createDiv({ cls: "modal-button-container" });
    const syncBtn = btnRow.createEl("button", {
      text: "Sync Now",
      cls: "mod-cta"
    });
    syncBtn.addEventListener("click", () => {
      this.close();
      this.options.onSync();
    });
    const declineBtn = btnRow.createEl("button", { text: "Not Now (pause 1h)" });
    declineBtn.style.marginLeft = "8px";
    declineBtn.addEventListener("click", () => {
      this.close();
      this.options.onDecline();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var GitSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "GitHub Sync Settings" });
    new import_obsidian.Setting(containerEl).setName("Vault path").setDesc(
      "Absolute path to the Obsidian vault directory (must be a git repo)."
    ).addText(
      (text) => text.setPlaceholder("/home/r/Documents/Obsidian").setValue(this.plugin.settings.vaultPath).onChange(async (value) => {
        this.plugin.settings.vaultPath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-sync pause duration (hours)").setDesc(
      "How long (in hours) to pause auto-sync after the user declines a notification."
    ).addSlider(
      (slider) => slider.setLimits(1, 24, 1).setValue(this.plugin.settings.autoPauseHours).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.autoPauseHours = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
